tests: Skip kern tests t35 and t40 unless there is enough disk space
t35 requires 500MB and t40 requires 100MB.

diff --git a/tests/kern/runtest b/tests/kern/runtest
--- a/tests/kern/runtest
+++ b/tests/kern/runtest
@@ -105,6 +105,21 @@ chmod 755 $PATH_MNTDIR $PATH_EXPDIR
 export PATH_EXPDIR
 export PATH_MNTDIR
 
+# t35 and t40 requires a certain amount of disk space
+# It's not possible to check until $PATH_MNTDIR is created
+case "$TEST" in
+	t35|t40)
+		avail=$(df -B1024K --output=avail "$PATH_MNTDIR" | tail -n1)
+		case "$TEST" in
+			t35) required=500;;
+			t40) required=100;;
+		esac
+		if [ "$avail" -lt "$required" ]; then
+			echo "Requires ${required}MB free space on $PATH_MNTDIR, only ${avail}MB available" >"$TEST.out"
+			exit 77
+		fi;;
+esac
+
 export MALLOC_CHECK_=3
 
 # t00 is a special interactive test, not normally run
