Replace diodexp with diodcat
The diodcat utility can cat any arbitrary file on a diod server
from user space, subject to the same authentication/authorization
rules as any diod client.

auto.diod is modified to use this utility to cat the diod server's
/proc/mounts to construct key matches, rather than cat the diodctl
exports pseudo-file using diodexp.  The upside of this change is
that a special purpose utility gets replaced with a general one,
and the only reason LLNL needs diodctl in diod 1.0 goes away.
The downside is that the server's /proc has to be made readable, and
requests for unexported file systems will trigger a (failing) mount
request instead of failing in the automouter key lookup.

diff --git a/scripts/auto.diod.in b/scripts/auto.diod.in
--- a/scripts/auto.diod.in
+++ b/scripts/auto.diod.in
@@ -1,10 +1,11 @@
-#!/bin/bash
+#!/bin/bash -e
 
 key="$1"
+[ -n "$key" ] || exit 0
 
 DIOD_MAP=/d
 DIOD_SYSCONF=@X_SYSCONFDIR@/sysconfig/auto.diod
-DIOD_DIODEXP=@X_SBINDIR@/diodexp
+DIOD_DIODCAT=@X_SBINDIR@/diodcat
 DIOD_SERVERS=""
 
 if [ -r $DIOD_SYSCONF ]; then
@@ -14,10 +15,16 @@ if [ -z "$DIOD_SERVERS" ]; then
     echo "auto.diod: DIOD_SERVERS is not set" >&2
     exit 1
 fi
-if ! [ -x $DIOD_DIODEXP ]; then
-    echo "auto.diod: could not execute $DIOD_DIODEXP" >&2
+if ! [ -x $DIOD_DIODCAT ]; then
+    echo "auto.diod: could not execute $DIOD_DIODCAT" >&2
     exit 1
 fi
-if [ -n "$key" ]; then
-    $DIOD_DIODEXP -a $key $DIOD_SERVERS
-fi
+
+$DIOD_DIODCAT -h $DIOD_SERVERS -a /proc mounts | awk '{print $2}' |\
+while read path; do
+    if [ "$key" == "ROOT" -a "$path" == "/" ] \
+         || [ "$key" == "$(echo $path|sed -e's/^\///' -e 's/\//./g')" ] \
+         || [ "$key" == "$(echo $path|sed -e's/^\///' -e 's/\//_/g')" ]; then
+        echo "-fstype=diod $DIOD_SERVERS:$path"
+    fi
+done
